export default {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_FILTER__MODES__PUBLICATION_LISTING_MODE:
    "SET_FILTER__MODES__PUBLICATION_LISTING_MODE",
  SET_FILTER__LISTS__PURCHASE_AVAILABILITY:
    "SET_FILTER__LISTS__PURCHASE_AVAILABILITY",
  SET_FILTER__LISTS__PRODUCT_TYPE: "SET_FILTER__LISTS__PRODUCT_TYPE",
  SET_FILTER__LISTS__VENDOR_NAME: "SET_FILTER__LISTS__VENDOR_NAME",
  SET_FILTER__QUERY: "SET_FILTER__QUERY",
};
